version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Zaq12wsx1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: moviedb
    networks:
      - movie-plus
  cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=test
networks:
  movie-plus:
    driver: bridge
