spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: false
  properties:
    hibernate: 
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
  redis:
    database: 0
    timeout: 6000
    
  messages:
    basename: messages,messages_system
    encoding: UTF-8
  cloud:
    mvc:
      token-relay: 
        enabled: false
    
eureka:
  instance:
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry : true

server:
  port: 8081

front-end:
  url:
    login: "localhost:8080"

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000 # Comma separated list of allowed origins
  cookie:
    name: XSRF-TOKEN

micro-service:
  config-service-uri: lb://config-service
  user-service-uri: lb://user-service
  reserve-service-uri: lb://reserve-service
  hall-service-uri: lb://hall-service
  movie-service-uri: lb://movie-service
  system-service-uri: lb://system-service
  api-gateway-uri: lb://api-gateway
 
logging:
  level:
    com.se.thanhvinh.simple: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
    
lombok:
  anyConstructor:
    addConstructorProperties: true