spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: Zaq12wsx1234
  redis:
    host: localhost
    port: 6379
    password: test
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Zaq12wsx1234
  security:
    user:
      name: admin
      password: passw@rd
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  level:
    org.springframework.security.web: DEBUG