server:
  port: 8088
  servlet:
    context-path: /system

logging:
  org:
    hibernate: ERROR
    springframework:
      web: ERROR
  root: ERROR

jwt:
  secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  expriration: 864000000

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

micro-service:
  movie-service:
  user-service:
  site-service:
  booking-service:
  system-service:
  
    